AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to deploy an endpoint using AWS Bedrock with the Llama 3.1 70B model.

Parameters:
  ModelName:
    Type: String
    Default: Llama3_1_70B
    Description: The name of the model to deploy.

  EndpointName:
    Type: String
    Default: Llama3_1_70B_Endpoint
    Description: The name of the endpoint to create.

  InstanceType:
    Type: String
    Default: ml.p3.16xlarge
    AllowedValues:
      - ml.p2.xlarge
      - ml.p2.8xlarge
      - ml.p2.16xlarge
      - ml.p3.2xlarge
      - ml.p3.8xlarge
      - ml.p3.16xlarge
    Description: The EC2 instance type to use for the model endpoint.

  S3BucketName:
    Type: String
    Default: llama-model-bucket
    Description: The name of the S3 bucket to store model data.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName

  Model:
    Type: AWS::Bedrock::Model
    Properties:
      ModelName: !Ref ModelName
      PrimaryContainer:
        Image: "amazonaws.com/bedrock/llama:3.1-70B"
        ModelDataUrl: !Sub "s3://${S3Bucket.BucketName}/path-to-your-model-data"
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn

  EndpointConfig:
    Type: AWS::Bedrock::EndpointConfig
    Properties:
      EndpointConfigName: !Ref EndpointName
      ProductionVariants:
        - VariantName: AllTraffic
          ModelName: !Ref Model
          InitialInstanceCount: 1
          InstanceType: !Ref InstanceType

  Endpoint:
    Type: AWS::Bedrock::Endpoint
    Properties:
      EndpointName: !Ref EndpointName
      EndpointConfigName: !Ref EndpointConfig

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ModelExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${S3Bucket.BucketName}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

Outputs:
  EndpointUrl:
    Description: The URL of the deployed endpoint.
    Value: !Sub "https://${Endpoint.EndpointName}.bedrock.amazonaws.com"
