services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:11434"]
    #   interval: 3s
    #   timeout: 1s
    #   retries: 2
    #   start_period: 12s
    # environment:
    #   - OLLAMA_HOST=0.0.0.0


  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - model_loader
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped


  model_loader:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c '
        curl http://ollama:11434/api/pull -d '\''{"name": "${LOCAL_LLM}"}'\'' 
      '
    depends_on:
      - ollama
    restart: unless-stopped


volumes:
  ollama: {}
  open-webui: {}