services:
  secad:
    build:
      context: .
      dockerfile: secad.Dockerfile
    restart: unless-stopped
    ports:
      - "8501:8501"
    env_file:
      - ./secad/.env
    depends_on:
      - vector-db
    networks:
      - ragnet
  
  vector-db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      LANG: en_US.utf8
      LANGUAGE: en_US:en
      LC_ALL: en_US.utf8
    ports:
      - "5432:5432"
    env_file:
      - ./secad/.env
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - ragnet
  
  # mermaid:
  #   build:
  #     context: ./mcp/mermaid
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - PORT=8000
  #   networks:
  #     - ragnet

networks:
  ragnet:
    driver: bridge

