services:
  secad:
    build:
      context: .
      dockerfile: devcontainer.Dockerfile
    volumes:
      - ../:/workspaces/secad:cached
    command: sleep infinity
    depends_on:
      - vector-db
    networks:
      - ragnet
  
  vector-db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      LANG: en_US.utf8
      LANGUAGE: en_US:en
      LC_ALL: en_US.utf8
    env_file:
      - ../secad/.env
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - ragnet

networks:
  ragnet:
    driver: bridge

