services:
  secad:
    # image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - ../:/workspaces/secad:cached
    command: sleep infinity
    depends_on:
      - vector-db
  
  vector-db:
    # image: ankane/pgvector:latest
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
      LANG: en_US.utf8
      LANGUAGE: en_US:en
      LC_ALL: en_US.utf8
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U langflow"]
    #   # test: ["CMD-SHELL", "psql -U langflow -d langflow -c 'SELECT extname FROM pg_extension WHERE extname = \'vector\';'"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
      # start_period: 30s
    networks:
      - ragnet

networks:
  ragnet:
    driver: bridge

